apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  steps:
    - name: lint
      image: python:3.8
      script: |
        pip install flake8
        flake8 .

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
    - name: test
      image: python:3.8
      script: |
        pip install pytest
        pytest

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  steps:
    - name: build
      image: docker
      script: |
        docker build -t my-microservice .

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  steps:
    - name: deploy
      image: 'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cee5e12a3b23bcfe1d06a3f5b9eeec20b48b2c30'
      script: |
        oc apply -f k8s/deployment.yaml

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-workspace
spec:
  workspaces:
    - name: output
  steps:
    - name: cleanup
      image: 'alpine'
      script: |
        rm -rf $(workspaces.output.path)/*

       
